[alembic]
script_location = alembic
prepend_sys_path = .
version_path_separator = os

# Logging deliberately left minimal – iotta manages its own logging
[loggers]
keys = root

[handlers]
keys =

[formatters]
keys =

[logger_root]
level = CRITICAL
handlers =
